import Image from 'next/image'
import Link from 'next/link'
import { ASSETS, AMAZON_URL, ContactForm, Newsletter, PageShell, ProductCard, ProductPage } from '@/components/lufu-site'

export default async function RoutePage({ params }: { params: Promise<{ slug: string[] }> }) { const { slug } = await params; const path = slug.join('/')
 if (path === 'products/lip-oil') return <ProductPage product="lip-oil" />
 if (path === 'products/moisturizer') return <ProductPage product="moisturizer" />
 if (path === 'products') return <PageShell><main><section className="max-w-7xl mx-auto px-6 py-20 md:py-28"><p className="text-xs tracking-[0.3em] uppercase text-[#8E776A] mb-5">The LUFU collection</p><h1 className="text-6xl md:text-8xl mb-6">Beauty, <em className="font-normal">simplified.</em></h1><p className="max-w-xl text-lg leading-7">Thoughtful essentials for the rituals that are uniquely yours.</p></section><section className="max-w-7xl mx-auto px-6 pb-24 grid md:grid-cols-2 gap-8"><ProductCard slug="lip-oil" image={ASSETS.lipOil}/><ProductCard slug="moisturizer" image={ASSETS.product1}/></section></main></PageShell>
 const pages: Record<string, {eyebrow:string,title:string,body:React.ReactNode}> = { story:{eyebrow:'Our story',title:'Born from a Vision. Built with Purpose.',body:<><p>LUFU Beauty was founded in 2026 with a vision to combine quality, confidence and everyday beauty with a unique, memorable global identity.</p><p>The brand was created after nearly a year of consideration and is built with a long-term vision of becoming a trusted international beauty brand.</p><p>LUFU Beauty puts customers and product quality first and is committed to thoughtful products, high standards and continuous improvement.</p><p className="text-3xl mt-12">LUFU Beauty — Beauty for Every Day. Confidence for Everywhere.</p></>}, philosophy:{eyebrow:'Our philosophy',title:'Beauty should feel personal, effortless, and empowering.',body:<><p>We believe beauty belongs in the everyday — in the small rituals that help you feel more like yourself.</p><p>Our focus is simple: quality, thoughtful product development, customer satisfaction, and products that fit naturally into your routine.</p><p>As LUFU grows globally, our commitment stays the same: create with intention, listen closely, and make beauty feel yours.</p></>}}
 if (pages[path]) { const p=pages[path]; return <PageShell><main><section className="max-w-4xl mx-auto px-6 py-24 md:py-36"><p className="text-xs tracking-[0.3em] uppercase text-[#8E776A] mb-6">{p.eyebrow}</p><h1 className="text-5xl md:text-7xl leading-tight mb-16">{p.title}</h1><div className="max-w-2xl space-y-7 text-lg leading-8">{p.body}</div></section></main></PageShell> }
 if (path === 'contact') return <PageShell><main><section className="max-w-7xl mx-auto px-6 py-20 md:py-28 grid md:grid-cols-2 gap-16"><div><p className="text-xs tracking-[0.3em] uppercase text-[#8E776A] mb-5">Get in touch</p><h1 className="text-6xl md:text-8xl mb-8">We&apos;d love<br/><em className="font-normal">to hear from you.</em></h1><div className="space-y-3 text-sm leading-6"><p>lufubeauty1@gmail.com</p><p>(540) 892-4071</p><p>United States</p></div></div><ContactForm/></section></main></PageShell>
 return <PageShell><main className="min-h-[50vh] flex items-center justify-center"><div className="text-center"><h1 className="text-6xl mb-5">Page not found</h1><Link className="btn-primary inline-block" href="/">Return home</Link></div></main></PageShell>
}
